[package]
name = "geese_pool"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/DouglasDwyer/geese_pool"
readme = "README.md"
description = """
Message-passing system for networking with Geese.
"""

[dependencies]
geese = "0.1.10"
takecell = "0.1.1"