[package]
name = "geese_pool"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
geese = "0.1.9"
takecell = "0.1.1"